org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.99
neo_version_range=[21.1.0,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=ipv6lanapi
mod_name=IPv6 LAN API
mod_license=MIT
mod_version=1.0.4
mod_group_id=com.example.ipv6lanapi
mod_authors=Mono2023
mod_description=Expose public IPv6 address via Web API when LAN world is opened