modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="IPv6 LAN API"
description='''Expose public IPv6 address via Web API when LAN world is opened'''
authors="Mono2023"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="mixins.ipv6lanapi.json"